Revert "Extract shared setup"
Run /./.github/actions/setup
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/net.twisterrob.libraries/net.twisterrob.libraries/.github/actions/setup'. Did you forget to run actions/checkout before running your local action?

This reverts commit 7f5684f855592b4f0a37f2ba607cf8dbf947c061.