Remove unnecessary classpath, but now the weirdest error... no suitable method found for exactlyOneOf
> Task :lib:hamcrest:compileJava FAILED
twister-lib-java\lib\hamcrest\src\main\java\net\twisterrob\test\hamcrest\Matchers.java:27: error: no suitable method found for exactlyOneOf(List<Matcher<? super T#1>>)
                return Matchers.exactlyOneOf(Arrays.asList(matchers));
                               ^
    method Matchers.<T#2>exactlyOneOf(Iterable<Matcher<? super T#2>>) is not applicable
      (inference variable T#3 has incompatible bounds
        equality constraints: Matcher<? super CAP#1>
        lower bounds: Matcher<? super T#1>)
    method Matchers.<T#1>exactlyOneOf(Matcher<? super T#1>...) is not applicable
      (cannot infer type-variable(s) T#1
        (varargs mismatch; no instance(s) of type variable(s) T#3 exist so that List<T#3> conforms to Matcher<? super T#1>))
  where T#1,T#2,T#3 are type-variables:
    T#1 extends Object declared in method <T#1>exactlyOneOf(Matcher<? super T#1>...)
    T#2 extends Object declared in method <T#2>exactlyOneOf(Iterable<Matcher<? super T#2>>)
    T#3 extends Object declared in method <T#3>asList(T#3...)
  where CAP#1 is a fresh type-variable:
    CAP#1 extends Object super: T#1 from capture of ? super T#1
1 error