Fix illegal stringer, type of mActive changed in https://github.com/androidx/androidx/commit/2486bb824eb9ec60da4a3c55a1764ad376dc6ce3
That caused
Cannot process androidx.fragment.app.FragmentManagerState@19122a93 via androidx.fragment.app.SupportFragmentManagerStateStringer@1b3ecf27
java.lang.IllegalArgumentException: Object [FragmentState{net.twisterrob.inventory.android.fragment.data.ItemViewFragment (c6cd39da-5d31-4c60-9573-b469e4397c87)}: id=0x7f0900e2] must be of an array type.
	at net.twisterrob.java.utils.ArrayTools.safeLength(ArrayTools.java:62)
	at androidx.fragment.app.SupportFragmentManagerStateStringer.toString(SupportFragmentManagerStateStringer.java:19)
	at androidx.fragment.app.SupportFragmentManagerStateStringer.toString(SupportFragmentManagerStateStringer.java:9)
	at net.twisterrob.java.utils.tostring.ToStringer.process(ToStringer.java:101)
	at net.twisterrob.java.utils.tostring.ToStringer.process(ToStringer.java:92)
	at net.twisterrob.java.utils.tostring.ToStringer.item(ToStringer.java:212)
	at net.twisterrob.android.utils.tostring.stringers.detailed.BundleStringer.toString(BundleStringer.java:22)
	at net.twisterrob.android.utils.tostring.stringers.detailed.BundleStringer.toString(BundleStringer.java:13)
	at net.twisterrob.java.utils.tostring.ToStringer.process(ToStringer.java:101)
	at net.twisterrob.java.utils.tostring.ToStringer.toString(ToStringer.java:82)
	at net.twisterrob.android.utils.tools.StringerTools.toString(StringerTools.java:27)
	at net.twisterrob.android.utils.log.LoggingDebugProvider$LoggingHelper.log(LoggingDebugProvider.java:21)
	at net.twisterrob.android.utils.log.LoggingFragment.log(LoggingFragment.java:216)
	at net.twisterrob.android.utils.log.LoggingFragment.onViewStateRestored(LoggingFragment.java:97)
	at net.twisterrob.inventory.android.fragment.data.BaseGalleryFragment.onViewStateRestored(BaseGalleryFragment.java:131)
	at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:577)
	at androidx.fragment.app.FragmentStateManager.restoreViewState(FragmentStateManager.java:356)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1201)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at net.twisterrob.android.utils.log.LoggingActivity.onStart(LoggingActivity.java:108)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1220)
	at android.app.Activity.performStart(Activity.java:5953)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
	at android.app.ActivityThread.access$800(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)