com.android.builder.errors.EvalIssueException: The option 'android.disableAutomaticComponentCreation' is deprecated. It was removed in version 8.0 of the Android Gradle plugin. Please remove it from `gradle.properties`.